//muestra todas las entradas de mascotas
GET http://localhost:8000/mascotas
Content-Type: application/json

### 
//muestra una entrada de mascota según id
GET http://localhost:8000/mascotas/543c2857-5b5a-4e61-b016-bb9ecfdc8a23
Content-Type: application/json

###
//borra 1 elemento mascota según id
DELETE http://localhost:8000/mascotas/20c23c88-8692-4349-8328-543156019a86
















###
//obtener una mascota según su compatibilidad con perros (filtro)
GET http://localhost:8000/mascotas?compatibilidad=perro

###
//obtener una mascota según su tamaño con mediano (filtro)
GET http://localhost:8000/mascotas?tamaño=mediano

###
//obtener una mascota según su raza con gato (filtro)
GET http://localhost:8000/mascotas?raza=gato

###
//obtener una mascota según su tamaño y sexo con mediano y F (filtro)
GET http://localhost:8000/mascotas?tamaño=mediano&sexo=F