//muestra todos los usuarios de refugios
GET http://localhost:8000/usuarios-refugios
Content-Type: application/json

###
//muestra una entrada de usuario-refugio según id
GET http://localhost:8000/usuarios-refugios/d8130110-afde-4ffd-96dd-17c9963e37e3
Content-Type: application/json


###
//borra 1 elemento usuario-refugio según id
DELETE http://localhost:8000/usuarios-refugios/f2f23e60-238d-4671-8b27-228697671680

###
POST http://localhost:8000/usuarios_refugios 
Content-Type: application/json

{   
    "nombre": "Ana",
    "apellido": "Lopez",
    "refugio": "El Campito",
    "provincia": "Buenos Aires",
    "localidad": "-",
    "mail": "analopez@gmail.com",
    "telefono": 46545631,
    "puntuacion": 8 
}