//muestra todos los usuarios adoptantes
GET http://localhost:8000/usuarios-adoptantes
Content-Type: application/json

### 
//muestra una entrada de usuario-adoptante según id
GET http://localhost:8000/usuarios-adoptantes/3271865c-c600-417a-a148-43f04c3444e3
Content-Type: application/json


###
//borra 1 elemento usuario-adoptante según id
DELETE http://localhost:8000/usuarios-adoptantes/ecc5f773-550c-484e-985e-674269443e51
