//muestra todas las entradas de mascotas
GET http://localhost:8000/mascotas
Content-Type: application/json


### 
//muestra todos los refugios
GET http://localhost:8000/usuarios-refugios
Content-Type: application/json

### 
//muestra una entrada según id
GET http://localhost:8000/mascotas/1
Content-Type: application/json

###
//borra 1 elemento
DELETE http://localhost:8000/mascotas/2
