//muestra todas las entradas de mascotas
GET http://localhost:8000/mascotas
Content-Type: application/json

### 
//muestra todos los usuarios de refugios
GET http://localhost:8000/usuarios-refugios
Content-Type: application/json

### 
//muestra todos los usuarios adoptantes
GET http://localhost:8000/usuarios-adoptantes
Content-Type: application/json

### 
//muestra una entrada de mascota según id
GET http://localhost:8000/mascotas/1
Content-Type: application/json

###
//obtener una mascota según su compatibilidad con perros
GET http://localhost:8000/mascotas?compatibilidad=perro

###
//muestra una entrada de usuario-refugio según id
GET http://localhost:8000/usuarios-refugios/1
Content-Type: application/json

###
//obtener un usuario según su provincia
GET http://localhost:8000/usuarios-adoptantes?provincia=Córdoba

###
//borra 1 elemento mascota según id
DELETE http://localhost:8000/mascotas/2

//borra 1 elemento usuario-refugio según id
DELETE http://localhost:8000/usuarios-refugios/2