//post nueva entrada: mascota
POST http://localhost:3306/adoptaditos/mascotas
Content-Type: application/json 

{
    "nombre": "Pepe",
    "raza": "perro",
    "edad": 5,
    "tamanio": "grande",
    "zona": "Barracas",
    "especial": false,
    "sexo": "M",
    "compatibilidad": "perro",
    "usuariosRefugioId": null,
    "usuariosAdoptanteId": null
}

###
PUT http://localhost:8000/mascotas/1
Content-Type: application/json

{
    "nombre": "Morgan",
    "raza": "loro",
    "edad": 8

}