# @name login
POST http://localhost:8000/login
Content-Type: application/json

{
  "username":"refugio",
  "password":"123456"
}

###
//post nueva entrada: mascota - requiere estar logeado
POST http://localhost:8000/mascotas
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre": "ona",
  "raza": "perro",
  "edad": 5,
  "tamanio": "mediano",
  "zona": "Villa del Parque",
  "especial": false,
  "sexo": "F",
  "compatibilidad": "ninguno"
}

###
//post nueva entrada: usuario-refugio - requiere estar logeado
POST http://localhost:8000/usuarios-refugios
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre": "Ana",
  "apellido": "Gomez",
  "refugio": "Patitas",
  "provincia": "CABA",
  "localidad": "CABA",
  "mail": "anagomez@gmail.com",
  "telefono": 4545546,
  "puntuacion": 7
}

###
//post nueva entrada: usuario-adoptante - requiere estar logeado
POST http://localhost:8000/usuarios-adoptantes
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre": "Mario",
  "apellido": "Lopez",
  "provincia": "Santa Fe",
  "localidad": "Rosario",
  "mail": "mariolopez@gmail.com",
  "telefono": 1564653,
  "puntuacion": 7
}


###
//modificar una entrada de mascota
PUT http://localhost:8000/mascotas/1
Content-Type: application/json

{
  "id": 1,
  "nombre": "Morgan",
  "raza": "perro",
  "edad": 8,
  "tamaño": "mediano",
  "zona": "Devoto",
  "especial": false,
  "sexo": "M",
  "compatibilidad": "perro, gato"
}

###
//modificar una entrada de usuario-refugio
PUT http://localhost:8000/usuarios-refugios/1
Content-Type: application/json

{
  "nombre": "Mariana",
  "apellido": "Alvarez",
  "refugio": "Patitas",
  "provincia": "Córdoba",
  "localidad": "Córdoba",
  "mail": "marianaalvarez@gmail.com",
  "telefono": 65653346,
  "puntuacion": 8
}

###
//modificar una entrada de usuario-adoptante
PUT http://localhost:8000/usuarios-refugios/1
Content-Type: application/json

{
  "nombre": "Gabriel",
  "apellido": "Alvarez",
  "provincia": "Córdoba",
  "localidad": "Córdoba",
  "mail": "gabrielalvarez@gmail.com",
  "telefono": 65653346,
  "puntuacion": 8,
  "publicacionesGuardadas": []
}