# @name login
POST http://localhost:8000/login
Content-Type: application/json

{
  "username":"refugio",
  "password":"123456"
}

###
//post nueva entrada: mascota - requiere estar logeado
POST http://localhost:8000/mascotas
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre": "Maki",
  "raza": "gato",
  "edad": 1,
  "tamanio": "chico",
  "zona": "Flores",
  "especial": false,
  "sexo": "F",
  "compatibilidad": "gato"
}

###
//post nueva entrada: usuario-refugio - requiere estar logeado
POST http://localhost:8000/usuarios-refugios
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre": "Ana",
  "apellido": "Gomez",
  "refugio": "Patitas",
  "provincia": "CABA",
  "localidad": "CABA",
  "mail": "anagomez@gmail.com",
  "telefono": 4545546,
  "puntuacion": 7
}

###
//post nueva entrada: usuario-adoptante - requiere estar logeado
POST http://localhost:8000/usuarios-adoptantes
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "nombre": "Juan",
  "apellido": "Perez",
  "provincia": "Santa Fe",
  "localidad": "Rosario",
  "mail": "juanperez@gmail.com",
  "telefono": 544232158,
  "puntuacion": 9
}


###
//modificar una entrada de mascota
PUT http://localhost:8000/mascotas/543c2857-5b5a-4e61-b016-bb9ecfdc8a23
Content-Type: application/json

{
  "nombre": "Stitch",
  "raza": "perro",
  "edad": 8,
  "tamanio": "mediano",
  "zona": "Devoto",
  "especial": false,
  "sexo": "M",
  "compatibilidad": "perro",
  "usuariosRefugioId": null,
  "usuariosAdoptanteId": null

}

###
//modificar una entrada de usuario-refugio
PUT http://localhost:8000/usuarios-refugios/1
Content-Type: application/json

{
  "nombre": "Mariana",
  "apellido": "Alvarez",
  "refugio": "Patitas",
  "provincia": "Córdoba",
  "localidad": "Córdoba",
  "mail": "marianaalvarez@gmail.com",
  "telefono": 65653346,
  "puntuacion": 8
}

###
//modificar una entrada de usuario-adoptante
PUT http://localhost:8000/usuarios-refugios/1
Content-Type: application/json

{
  "nombre": "Gabriel",
  "apellido": "Alvarez",
  "provincia": "Córdoba",
  "localidad": "Córdoba",
  "mail": "gabrielalvarez@gmail.com",
  "telefono": 65653346,
  "puntuacion": 8,
  "publicacionesGuardadas": []
}